.TH yENV_user· 3 2024-may "linux" "interfacing with micro, code-inclusion version"

.SH NAME
yENV \- provide consistent linux filesystem and security services

.SH PATRON (see HERITAGE at bottom for more)
tartarus-eeroeis (murky one) linux filesystem and security services

.SH IMAGERY
dreaded place of darkness and punishment reserved for the worst sinners

.SH SUMMARY (see yENV (7) for more information)
yENV and yENV_uver allow for consistent auditing and access to the
linux security system so that many of my programs can take advantage
of my latest updates with little work.

.SH SERIOUS FOREWARNING
i am a crazy, selfish, dog-fooding c-programmer.  my code tends to be
experimental and constantly evolving.  my point is NOT to be the best, it is
to challenge myself, build from scratch, and allow fast problem solving.

.SH DOCUMENTATION
.nf
yENV (3)           interfacing with yENV in general
yENV_uver (3)      interfacing with micro, code-inclusion version
yENV_peek (3)      interfacing with file content review
yENV_touch (3)     interfacing with creation/removal functions
yENV_audit (3)     interfacing with auditing functions
.B yENV_user (3)´´´´´´interfacing with users/owners
yENV_group (3)     interfacing with groups
yENV_perms (3)     interfacing with permissions
yENV_score (3)     interfacing with application scoring
yENV (7)           decision rationale, scope, and objectives

.SH TABLE OF CONTENTS
.nf  
a) overview        quick summary
b) files           data access and modification
c) synopsis        function overview
d) access keys     consistent ways to find entries
e) fullsome        maximal interface
f) simplified      useful simpifiers for the fullsome version
g) data access     debugging, unit testing, and reporting
h) unit-test       unit testing specific functions

.SH A) OVERVIEW
yENV provides a standardized interface for inquiring about linux user data
(the owners of filesystem objects).  i use this ability through-out my programs
to verify and secure my environments and content.  the setting part is handled
in yENV_audit (3).

.SH B) FILES
yENV uses the /etc/passwd file for read-only data extraction.  yENV can modify
the user assignment of a filesystem entry, but not its contents.

the user test support functions below specifically use "useradd" and "userdel"
to update /etc/passwd so that it stays fully system controlled.

.SH C) SYNOPSIS
.nf
usage is noted on the far-left of each entry...
   ! means once-per-program
   ¼ primary interface
   ´ every program
   · not in every program

---fullsome------------------------------------
¼  char     yENV_user_full       (char  <type>, ´´´);
·  char     yENV_user_data       (char  <type>, ´´´);

---simplifiers---------------------------------
·  char     yENV_user            (char* <text>, ´´´);
·  char     yENV_user_uid        (char <type>, int <value>, ´´´);

---data-access---------------------------------
·  int      yENV_user_count      (void);
·  char*    yENV_user_by_cursor  (char  <dir));
·  char*    yENV_user_by_text    (char* <text));

---unit-testing--------------------------------
·  char     yENV_user_add        (char* (name>, ´´´);
·  char     yENV_user_del        (char* (name>);
·  char     yENV_user_purge      (void);
·  char     yENV_user_switch     (char* (name>);

.SH D) ACCESS KEYS
users can be queried two different ways -- user name and user id.

.SH E) FULLSOME
this interface is the most expansive one, adding many non-typical fields that
remove a great deal of reduntant effort from my security related programs
like themis, argus, hermes, etc.

there are two functions to get at this data, one is flexible (yENV_user_full)
and the other more direct (yENV_user_data).  yENV_user_full uses
yENV_user_data at is core.

.SS char  yENV_user_full (char <a_type>, char* <a_text>, ´´´);
gathers extensive data based on the access keys above.  this is the most common
external interface as it is the most forgiving.  if you pass an at-sign (@)
as string, the default of the current login will be used.

.RS 3
.B char <a_type> the filesystem entry type, e.g., YENV_DIR
.RE

.RS 3
.B char *<a_text> find string -- ¶root¶ or ¶1000¶
.RE

.RS 3
.B char *<r_name>, returns the user name
.RE

.RS 3
.B int *<r_uid>, returns the user id (uid)
.RE

.RS 3
.B int *<r_gid>, returns the user default group id (gid)
.RE

.RS 3
.B char *<r_home>, returns user's home directory
.RE

.RS 3
.B char *<r_shell>, returns user's default shell
.RE

.RS 3
.B char *<r_handle>, returns string ¶name¶, ¶uid¶, or ¶default¶
.RE

.RS 3
.B char* <r_quality>, returns judgement on user name
.RE

.RS 3
.B char *<r_active>, returns judgement on whether user is active
.RE

.RS 3
.B char *<r_login>, returns judgement on ability to login
.RE

.RS 3
.B char *<r_groups>, returns number of groups assigned
.RE

.RS 3
.B char *<r_gnames>, returns list of groups assigned
.RE

.RS 3
.B char *<r_gids>, returns list of gids assigned
.RE

.SS char  yENV_user_data (char <a_type>, ´´´);
underlying foundation of yENV_user_full, but less flexible.  instead of using
a_text to pass any of the access keys, they are passed in their respective
fields.  the a_type field is used to determine the method of id.

.RS 3
.B char <a_type>, 'n' use name to get data or 'i' to use uid.
.RE

.RS 3
.B char *<b_name>, two way pointer for name
.RE

.RS 3
.B int *<b_gid>, two-way pointer for gid
.RE

the rest of the fields are exactly the same as yENV_user_full.

.SH F) SIMPLIFIED

.SS char  yENV_user (char* <text>, ´´´);
simpilied version of yENV_user_full that only returns r_name and ruid.

.SS char  yENV_user_octal (char <a_type>, int <a_value>, ´´´);
another simplication to allow yENV_user to be called with a numeric uid value
rather than as a string.  it avoids extra programming later.

.SH G) DATA ACCESS
to better enable reporting, unit testing, and debugging, i have added
a couple standard data access methods.

.SS char  yENV_user_count (void)
returns the number of users in passwd

.SS char* yENV_user_by_cursor (char <dir>)
returns a detailed string with all data based on standard cursoring

.SS char* yENV_user_by_text (char* <text>)
returns a detailed string with all data based on the two methods

.SH H) UNIT TEST SUPPORT
to make user testing a little more easy and avoid repeated code, i have added
a couple support functions.  these functions use useradd and userdel to
keep /etc/passwd full under system control.

.SS char  yENV_user_add (char* <text>, ´´´);
creates a unit test user on the system with specialized name (USR_´´´)

.SS char  yENV_user_del (char* <text>);
removes a unit test user on the system with specialized name (USR_´´´)

.SS char  yENV_user_purge (<void>)
removes all unit test users with specialized name (USR_´´´)

.SS char  yENV_user_switch (char* <text>);
switches to new user, very simplistic

.SH BUGS
yENV is incredibly stable for me, but if anyone else used it it might explode
and take the universe with it.

.SH COLOPHON
this page is part of a documentation package meant to make the use of the
heatherly tools easier and faster

