.TH yENV_file· 3 2024-may "linux" "interfacing with micro, code-inclusion version"

.SH NAME
yENV \- provide consistent linux filesystem and security services

.SH PATRON (see HERITAGE at bottom for more)
tartarus-eeroeis (murky one) linux filesystem and security services

.SH IMAGERY
dreaded place of darkness and punishment reserved for the worst sinners

.SH SUMMARY (see yENV (7) for more information)
yENV and yENV_uver allow for consistent auditing and access to the
linux security system so that many of my programs can take advantage
of my latest updates with little work.

.SH SERIOUS FOREWARNING
i am a crazy, selfish, dog-fooding c-programmer.  my code tends to be
experimental and constantly evolving.  my point is NOT to be the best, it is
to challenge myself, build from scratch, and allow fast problem solving.

.SH DOCUMENTATION
.nf
yENV (3)           interfacing with yENV in general
yENV_uver (3)      interfacing with micro, code-inclusion version
yENV_peek (3)      interfacing with file content review
yENV_entry (3)     interfacing with creation/removal functions
yENV_audit (3)     interfacing with auditing functions
.B yENV_file (3)´´´´´´interfacing with file open/close functions
yENV_user (3)      interfacing with users/owners
yENV_group (3)     interfacing with groups
yENV_perms (3)     interfacing with permissions
yENV_score (3)     interfacing with application scoring
yENV_base (3)      interfacing with whoami function
yENV (7)           decision rationale, scope, and objectives

.SH TABLE OF CONTENTS
.nf  
A) overview        quick summary
B) synopsis        function overview
C) ope             verify and open file
D) close           close file
E) read            read next record

.SH A) OVERVIEW
yENV provides a confirmation interface for openning and closing files, where
it checks whether the file exists and is properly secured before using.
very, very, very bloody useful in secure programs.

.SH B) SYNOPSIS
.nf
---openning------------------------------------
·  char     yENV_open_full       (´´´);
·  char     yENV_open            (´´´);

.nf
---closing-------------------------------------
·  char     yENV_close_full      (´´´);
·  char     yENV_close           (´´´);

.nf
---reading-------------------------------------
·  char     yENV_read            (´´´);

.SH C) OPENNING
openning regular files is easy, but doing it consistently and carefully is
fussy and time-consuming.  these functions remove a great deal of reduntant
effort from my everyday applications (high security is yAUDIT).

.SS char  yENV_open_full (´´´)
detailed method for openning files to meet all my needs.

.B char*²a_label²²²[LEN_LABEL]
.RS 3
short label for debugging and tracing
.RE

.B char*²²a_dir²²²²²[LEN_PATH]
.RS 3
directory storing file
.RE

.B char*²²a_name²²²²[LEN_HUND]
.RS 3
name of the file itself
.RE

.B char²²²a_mode
.RS 3
r=text read, R=binary read, w=text write, W=binary write
.RE

.B char*²²r_mode²²²²[LEN_SHORT]
.RS 3
two-character linux mode, i.e., "rt" for a_mode of 'r'
.RE

.B char*²²r_note²²²²[LEN_LABEL]
.RS 3
longer mode description, i.e., "reading as text" for a_mode of 'r'
.RE

.B char*²²r_full²²²²[LEN_PATH]
.RS 3
fully concatinated, cleaned up, name of file
.RE

.B FILE**²b_file
.RS 3
actual file pointer, must start be NULL to open.
.RE

.B return code
.RS 3
1 for open, negative for trouble
.RE

NOTE : you can put entire dir/file in a_dir and the function will sort that
out automatically.

.SS char  yENV_open (´´´)
simplified interface which in turn calls yENV_open_full using a_dir, a_file,
a_mode, and r_full.

.SH D) CLOSING
closing file is much simplier, but this function is a pair to yENV_open_full,
checks the pointer, and grounds after closing.

.SS char  yENV_close_full (´´´)
opens a file if it meets all the security requirements.

.B char*²²a_label²²²[LEN_LABEL]
.RS 3
short label for debugging and tracing
.RE

.B FILE**²b_file
.RS 3
actual file pointer, must start be set to close.
.RE

.B char²²c_sync
.RS 3
y = sync drives after closing
.RE

.B return code
.RS 3
1 for closed, negative for trouble
.RE

.SS char  yENV_close (´´´)
simplified interface which in turn calls yENV_close_full using only b_file.

.SH E) READING
reading normal, everyday files is just a simple slog and one that i tire of
repeating ;) this function removes a great deal of reduntant effort from
my everyday applications in keeping counters and skipping empty records,
comments, etc.

.SS char  yENV_read (´´´)
more detailed interface for reading records from file.  there is no
simplified interface at this time.

.B FILE*²²a_file
.RS 3
actual file pointer, must be set to continue
.RE

.B char²²²c_comment
.RS 3
y = ignore any # prefixed line, - means keep #> and #@ lines
.RE

.B char²²²c_visible
.RS 3
y = convert ascii field sperator to visible (§)
.RE

.B int*²²²b_read
.RS 3
updates read counter every fgets ()
.RE

.B int*²²²b_accept
.RS 3
updates accept counter when usable record found and returns
.RE

.B char*²²b_curr²²²²[LEN_RECD]
.RS 3
latest usable record from file
.RE

.B char*²²r_prev²²²²[LEN_RECD]
.RS 3
previous usable record from file
.RE

.B return code
.RS 3
1 for closed, 0 for normal end-of-file, negative for trouble
.RE

.SH BUGS
yENV is incredibly stable for me, but if anyone else used it it might explode
and take the universe with it.

.SH COLOPHON
this page is part of a documentation package meant to make the use of the
heatherly tools easier and faster
